services:
  - type: web
    name: motta-carrozzeria
    env: node
    repo: https://github.com/assurdotrattinocorto-ux/motta-carrozzeria
    branch: main
    buildCommand: npm install && npm run build
    startCommand: node server/index.js
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_PATH
        value: ./database.db
      - key: CORS_ORIGIN
        fromService:
          type: web
          name: motta-carrozzeria
          property: url