services:
  - type: web
    name: motta-5
    env: node
    plan: free
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: motta5-database
          property: connectionString