services:
  - type: web
    name: motta5-server
    env: node
    plan: free
    buildCommand: npm install && cd client && npm install && npm run build && cd ..
    startCommand: node server/index.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: DATABASE_PATH
        value: ./database.db
      - key: JWT_SECRET
        value: motta_carrozzeria_secret_key_2024_render
      - key: CORS_ORIGIN
        value: https://motta-carrozzeria-9s5o.onrender.com